export const mockTraders = [
  {
    id: 1,
    name: 'Alice Johnson',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    performance: 32.5,
    followers: 1200,
    assets: ['AAPL', 'BTC', 'ETH'],
  },
  {
    id: 2,
    name: 'Bob Smith',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    performance: 27.1,
    followers: 980,
    assets: ['TSLA', 'ETH', 'SOL'],
  },
  {
    id: 3,
    name: 'Carol Lee',
    avatar: 'https://randomuser.me/api/portraits/women/68.jpg',
    performance: 45.3,
    followers: 1500,
    assets: ['GOOGL', 'BTC', 'ADA'],
  },
  {
    id: 4,
    name: 'David Kim',
    avatar: 'https://randomuser.me/api/portraits/men/45.jpg',
    performance: 38.7,
    followers: 1100,
    assets: ['AMZN', 'DOGE', 'XRP'],
  },
  {
    id: 5,
    name: 'Eva Green',
    avatar: 'https://randomuser.me/api/portraits/women/12.jpg',
    performance: 29.4,
    followers: 870,
    assets: ['NFLX', 'BTC', 'LTC'],
  },
  {
    id: 6,
    name: 'Frank Miller',
    avatar: 'https://randomuser.me/api/portraits/men/56.jpg',
    performance: 41.2,
    followers: 1340,
    assets: ['MSFT', 'ETH', 'BNB'],
  },
  {
    id: 7,
    name: 'Grace Park',
    avatar: 'https://randomuser.me/api/portraits/women/23.jpg',
    performance: 36.8,
    followers: 990,
    assets: ['FB', 'SOL', 'BTC'],
  },
  {
    id: 8,
    name: 'Henry Ford',
    avatar: 'https://randomuser.me/api/portraits/men/77.jpg',
    performance: 25.9,
    followers: 760,
    assets: ['TSLA', 'ADA', 'ETH'],
  },
  {
    id: 9,
    name: 'Ivy Chen',
    avatar: 'https://randomuser.me/api/portraits/women/35.jpg',
    performance: 48.1,
    followers: 1600,
    assets: ['AAPL', 'BTC', 'DOGE'],
  },
]; 